CREATE TABLE EMPLEADOS(
    NUMEMP INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    EDAD INT NOT NULL,
    OFICINA INT NULL,
    TITULO VARCHAR(30) NOT NULL,
    CONTRATO DATE NOT NULL,
    JEFE INT NULL,
    CUOTA FLOAT NOT NULL
);



SELECT *
FROM EMPLEADOS
;

SELECT NOMBRE, TITULO, CONTRATO
FROM EMPLEADOS;

SELECT NOMBRE, EDAD
FROM EMPLEADOS
ORDER BY EDAD DESC;

SELECT NOMBRE, OFICINA, TITULO, CUOTA, MIN(CONTRATO)
FROM EMPLEADOS;

SELECT NUMEMP,
        NOMBRE,
        VENTAS
FROM EMPLEADOS
WHERE EDAD > 40;

SELECT NOMBRE,
        OFICINA,
        CONTRATO
FROM EMPLEADOS
WHERE TITULO = "representante";